identifier: m04910je888epd9c
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: my-blog
homeFolder: C:\Users\redalyc\my-blog
distFolder: dist/my-blog
outDir: C:\Users\redalyc\my-blog\dist\static
handle404: ''
allowErrorCollect: false
